// Copyright 2022-2023 Travis Mick (@tmick0)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RGB_MATRIX_LED_COUNT 60
#define ANALOG_JOYSTICK_X_AXIS_PIN F5
#define ANALOG_JOYSTICK_Y_AXIS_PIN F4
#define POINTING_DEVICE_INVERT_X
#define ANALOG_JOYSTICK_SPEED_REGULATOR 5
#define ANALOG_JOYSTICK_SPEED_MAX 3
#define SCROLL_WAIT_PERIOD 10
